### ISSUE TITLE
Series of bugs

### ISSUE THREAD

**Issue by VoidPollo** [JuneDeveloper/Minecraft-Coordinate-Book#22]
**Describe the bugs**

- ~~Unable to use the right shift key to capitalize letters, when the right shift is pressed the character: " ŕ " gets typed.~~
- There is no typing cursor to navigate back and forth through the words/lines
- ~~Unable to use "Enter" to go to the next line in the note.~~
- ~~Keys like W A S D SPACE etc, make your character to move as you're typing.~~
- ~~Unable to leave backspace pressed to keep deleting.~~

**Other Info**

- System OS: Windows 11
- Mod version: 1.1.2
- Download page: Modrinth

**Comment by JWGardiner** [comment]
I'm unable to produce the W A S D bug, could be a difference between Windows and Linux.

I am working to improve how text is written, currently it's using my own (buggy) way of writing text.

There is no typing cursor currently - however arrow keys should still work.

I'll work to fix as many of these as I can for 1.1.3, but, really I need to re-write how text input is received from the user.

**Comment by VoidPollo** [comment]
Sorry, the W A S D was intentional by another mod, retested everything on a clean profile, everything else still stand on my bug report, except the " W A S D" one.

**Comment by JWGardiner** [comment]
Alright, I'm a little busy for the next week or so, but I'll get started sometime then.

**Comment by JWGardiner** [comment]
Having revisited this I do not think these are fixable yet - I need to redo the entire way text is written
I am currently going through and trying to fix this using the original way text is written but i believe it's too deeply integrated into the nbt data of the book (And there's no item to store the nbt data on)
Might be fixed in the next version, if not it will be a while

**Comment by JWGardiner** [comment]
I have found a new solution to the problem; using the code for signs i can fix some of the issues here.

**Comment by danielwerg** [comment]
> There is no typing cursor currently - however arrow keys should still work.
Using version `1.3.0+1.19` I'm not able to use arrow keys. Can't wait for cursor support!

**Comment by JuneDeveloper** [comment]
> > There is no typing cursor currently - however arrow keys should still work.
> 
> Using version `1.3.0+1.19` I'm not able to use arrow keys. Can't wait for cursor support!

Cursor support will be in the next version - currently the quilt/1.19 branch should be stable enough if you want to compile it.
I will close this issue as it is pretty much all done.
