### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by danielwerg** [JuneDeveloper/Minecraft-Coordinate-Book#31]
### It's not clear that "bookmark" button is in fact a button

I only realized it was a button after reading changelog

Possible fix: Add on hover effect like "delete/trash" and "arrow" icon does, add tooltip

### Change color of "bookmark" icon on current bookmarked page

There no way to tell if current page bookmarked or not without clicking "arrow" button

### Change or/and add tooltip to "arrow" button

It's not clear what `[←` or "arrow" button does without reading changelog

### Make all button icon in consistent style and color

I like how bookmark icon looks, "delete/trash" icon seems a bit too big to me, also it doesn't align with `( )` element

![2022-11-16_21-32-00](https://user-images.githubusercontent.com/35052399/202298830-f30d74f8-bddc-4393-9381-6b6019c14d2e.png)

**Comment by JuneDeveloper** [comment]
I was thinking about a way to work on making the UI more user friendly (Like you said, if you don't read the changelog you probably won't know what the arrow button does) but tooltips are a very good idea! I will try and implement this next update although it may come a bit later (Depending on how long other stuff takes)

**Comment by danielwerg** [comment]
Built from https://github.com/JuneDeveloper/Minecraft-Coordinate-Book/commit/7a28d13d81567655d0269f79cec326334694db73

Few problems:
- Bookmark button gone
- Cursor doesn't blink
- Cursor is too short
- Cursor moves text when in between characters

Here is example how vanilla book looks:

https://user-images.githubusercontent.com/35052399/202586153-ce11eee5-67f0-4e3c-a9dd-58ab58824380.mp4

**Comment by JuneDeveloper** [comment]
The bookmark button will be back soon, it's only gone temporarily. (Most likely later today)

I'm still working on the cursor, right now it only serves as a visual marker for the position when it's complete.

**Comment by danielwerg** [comment]
> The bookmark button will be back soon, it's only gone temporarily. (Most likely later today)
> 
> I'm still working on the cursor, right now it only serves as a visual marker for the position when it's complete.

Gotcha, thanks for update.

**Comment by JuneDeveloper** [comment]
https://user-images.githubusercontent.com/86971433/202759474-26dbece6-776f-4577-a5ed-2902e1798854.mp4

This should help clarify the purpose of the buttons
